package ma.gabCashRetracted.entities;

// Generated 31 janv. 2016 23:21:57 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Compte generated by hbm2java
 */
public class Compte implements java.io.Serializable {

	private Integer idCompte;
	private Client client;
	private Float montant;
	private Set<Transaction> transactions = new HashSet<Transaction>(0);

	public Compte() {
	}

	public Compte(Client client) {
		this.client = client;
	}

	public Compte(Client client, Float montant, Set<Transaction> transactions) {
		this.client = client;
		this.montant = montant;
		this.transactions = transactions;
	}

	public Integer getIdCompte() {
		return this.idCompte;
	}

	public void setIdCompte(Integer idCompte) {
		this.idCompte = idCompte;
	}

	public Client getClient() {
		return this.client;
	}

	public void setClient(Client client) {
		this.client = client;
	}

	public Float getMontant() {
		return this.montant;
	}

	public void setMontant(Float montant) {
		this.montant = montant;
	}

	public Set<Transaction> getTransactions() {
		return this.transactions;
	}

	public void setTransactions(Set<Transaction> transactions) {
		this.transactions = transactions;
	}

}
